name: Compile Sing-box Rulesets

# Trigger the workflow on push to the main branch and daily at midnight UTC
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  compile-rulesets:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner (Debian-based)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # This is required to push back to the repository

      # Step 2: Update and install necessary packages
      - name: Update and Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y sudo unzip curl wget

      # Step 3: Download the sing-box .deb package
      - name: Download sing-box
        run: |
          wget https://github.com/SagerNet/sing-box/releases/download/v1.10.5/sing-box_1.10.5_linux_amd64.deb

      # Step 4: Install sing-box
      - name: Install sing-box
        run: |
          sudo apt install -y ./sing-box_1.10.5_linux_amd64.deb
          rm sing-box_1.10.5_linux_amd64.deb

      # Step 5: Clone the Sing-box-rulesets repository
      - name: Clone Sing-box-rulesets Repository
        run: |
          git clone https://github.com/KexiChanProjectProxy/Sing-box-rulesets.git

      # Step 6: Compile each ruleset
      - name: Compile Rulesets
        run: |
          cd Sing-box-rulesets/list
          for i in *; do
            echo "Compiling ruleset: $i"
            sing-box rule-set compile "$i"
          done

      # Step 7: Commit and push changes
      - name: Commit and Push Changes to Sing-box-rulesets
        env:
          PAT_TOKEN-K: ${{ secrets.PAT_TOKEN-K }}
        run: |
          pwd  # Print current directory for debugging
          ls -la  # List files for debugging
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          echo $PAT_TOKEN-K | sha256sum
          # Commit only if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Auto compile and add rulesets [skip ci]"
            git push https://${{ secrets.PAT_TOKEN-K }}@github.com/KexiChanProjectProxy/Sing-box-rulesets.git main
          else
            echo "No changes to commit."
          fi